global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8001']
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:8002']
  - job_name: 'nvidia-gpu'
    static_configs:
      - targets: ['nvidia-exporter:9400']